%%{init: {'theme':'base', 'themeVariables': {'fontFamily':'Calibri'}}}%%
flowchart LR
    REC(("👤<br/>Receptionist"))
    TECH(("👤<br/>Technician"))
    BM(("👤<br/>Branch<br/>Manager"))

    subgraph SYSTEM["Phân hệ Lễ tân"]
        UC1((Mở ca<br/>đầu giờ))
        UC2((Theo dõi<br/>ca đang mở))
        UC3((Đóng ca<br/>cuối giờ))
        UC4((Xem báo cáo<br/>kết ca))
        UC5((Tạo đơn<br/>POS))
        UC6((Thêm nhanh<br/>SP/DV))
        UC7((Gắn khách<br/>vào đơn))
        UC8((Áp khuyến mãi<br/>voucher))
        UC9((Thanh toán<br/>đa phương thức))
        UC10((In/gửi<br/>hóa đơn))
        UC11((Lưu đơn tạm))
        UC12((Check-in<br/>quét thẻ/QR))
        UC13((Check-in<br/>thủ công))
        UC14((Trừ quota<br/>dịch vụ))
        UC15((Đặt lịch<br/>booking))
        UC16((Bán gói<br/>thành viên))
    end

    REC --> UC1
    REC --> UC2
    REC --> UC3
    REC --> UC5
    REC --> UC6
    REC --> UC7
    REC --> UC8
    REC --> UC9
    REC --> UC10
    REC --> UC11
    REC --> UC12
    REC --> UC13
    REC --> UC16

    TECH --> UC14
    TECH --> UC15

    BM --> UC4
    BM --> UC2
    BM --> UC3

    UC9 -.includes.-> UC10
    UC5 -.extends.-> UC6
    UC5 -.extends.-> UC7
    UC5 -.extends.-> UC8

    classDef actor fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef uc fill:#E1F5EE,stroke:#2C7A7B,color:#0F4C44

    class REC,TECH,BM actor
    class UC1,UC2,UC3,UC4,UC5,UC6,UC7,UC8,UC9,UC10,UC11,UC12,UC13,UC14,UC15,UC16 uc
