%%{init: {'theme':'base', 'themeVariables': {'fontFamily':'Calibri'}}}%%
flowchart LR
    CASH(("👤<br/>Cashier"))
    SM(("👤<br/>Store<br/>Manager"))
    VAT(("🌐<br/>E-invoice<br/>Provider"))
    PAY(("🌐<br/>Payment<br/>Gateway"))

    subgraph SYSTEM["Phân hệ POS bán hàng"]
        UC1((Mở ca<br/>đầu giờ))
        UC2((Tìm SP<br/>mã/quét barcode))
        UC3((Thêm vào<br/>giỏ hàng))
        UC4((Chọn khách<br/>hàng))
        UC5((Áp khuyến mãi<br/>voucher))
        UC6((Thanh toán<br/>cash/card/QR))
        UC7((Thanh toán<br/>chuyển khoản/nợ))
        UC8((In bill<br/>máy in nhiệt))
        UC9((Phát hành<br/>HDDT VAT))
        UC10((Tạm treo đơn<br/>parked order))
        UC11((Trả hàng<br/>hoàn đơn))
        UC12((Kiểm kê<br/>cuối ca))
        UC13((Đóng ca))
    end

    CASH --> UC1
    CASH --> UC2
    CASH --> UC3
    CASH --> UC4
    CASH --> UC5
    CASH --> UC6
    CASH --> UC7
    CASH --> UC8
    CASH --> UC9
    CASH --> UC10
    CASH --> UC11
    CASH --> UC12
    CASH --> UC13

    SM --> UC12
    SM --> UC13

    UC6 -.includes.-> UC8
    UC6 <-.gọi API.-> PAY
    UC9 <-.gọi API.-> VAT
    UC3 -.extends.-> UC2
    UC11 -.extends.-> UC6

    classDef actor fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef ext fill:#FEF3C7,stroke:#F59E0B,color:#78350F
    classDef uc fill:#E1F5EE,stroke:#2C7A7B,color:#0F4C44

    class CASH,SM actor
    class VAT,PAY ext
    class UC1,UC2,UC3,UC4,UC5,UC6,UC7,UC8,UC9,UC10,UC11,UC12,UC13 uc
