%%{init: {'theme':'base', 'themeVariables': {'fontFamily':'Calibri'}}}%%
stateDiagram-v2
    direction LR
    [*] --> PreOpen: Đăng nhập + chọn cơ sở
    PreOpen: Chưa vào ca

    PreOpen --> Open: Chọn cấu hình ca

    Open: Vào ca\n(Nhập tiền đầu ca)
    Open --> OnShift: Xác nhận vào ca\n(tiền > 0)
    Open --> PreOpen: Hủy

    OnShift: Đang ca\n(Đếm giờ + KPI)
    OnShift --> OnShift: Tạo đơn POS\n/ Check-in\n/ Trừ quota
    OnShift --> Close: Bấm "Kết thúc ca"

    Close: Đóng ca\n(Đối soát tiền xuất)
    Close --> Report: Xác nhận đóng\n(có thể ghi chú chênh lệch)

    Report: Báo cáo kết ca
    Report --> [*]: In/Xuất Excel\n/Gửi quản lý

    note right of OnShift
        Mọi đơn POS,
        check-in, trừ quota
        gắn vào ca này
    end note

    note right of Close
        Sau khi đóng,
        không tạo được
        đơn mới
    end note
