export interface ICustomerResponse {
  contactName: string;
  id: number;
  code?: string;
  profileLink?: string;
  name: string;
  gender?: number;
  age?: number;
  address?: string;
  phone?: string;
  phoneMasked?: string;
  phoneUnmasked?: string;
  email?: string;
  emailMasked?: string;
  birthday?: string;
  fmtBirthday?: string;
  areaId?: number;
  job?: string;
  maritalStatus?: number;
  childrenNum?: number;
  presenterId?: number;
  employeeId?: number;
  employeeName?: string;
  employeePhone?: string;
  employeeAvatar?: string;
  departmentName?: string;
  sourceId?: number;
  sourceName?: string;
  note?: string;
  healthHistoryOther?: string;
  userId?: number;
  cardId?: number;
  recommenderPhone?: string;
  bsnId?: number;
  fee?: number;
  paid?: number;
  debt?: number;
  returnedFee?: number;
  cardName?: string;
  serviceNum?: number;
  serviceChargeTotal?: number;
  productNum?: number;
  productChargeTotal?: number;
  branchId?: number;
  careerId?: number;
  careers?: unknown[];
  careerName?: string;
  cgpId?: number;
  avatar: string;
  firstCall: string;
  height: string;
  weight: string;
  profileStatus?: number;
  secondProfileLink?: string;
  secondProfileStatus?: number;
  relationshipId?: number;
  groupName?: string;
  contactCount: number;
  invoiceChargeTotal: number;
  dayNotContact: number;
  invoiceCount: number;
  lastBoughtDate: string;
  lastContactDate: string;
  customerExtraInfos: Record<string, unknown>[];
  timestamp?: number;
  custType?: number;
  trademark?: string;
  taxCode?: string;
  contactId?: number;
  employeeTitle?: string;
  contractId?: number;
  relationshipName?: string;
  cgpName?: string;
  lastSignDate?: string;
  totalRentedArea?: number | string;
  totalValueContract?: number;
  zaloUserId?: number | string;
  isExternal?: number;
  relationIds: number[];
  relations: Record<string, unknown>[];
  mapCustomerAttribute?: Record<string, unknown>;
  lstCustomerExtraInfo?: Record<string, unknown>[];
  telesaleCall?: Record<string, unknown>;
  syncTime?: string;
  saleAssignDate?: string;
  employeeAssignDate?: string;
}

export interface ICustomerInvoiceResponse {
  id: number;
  account: string;
  amount: number;
  amountCard: number;
  branchId: number;
  bsnId: number;
  customerId: number;
  customerName: string;
  debt: number;
  discount: number;
  employeeId: number;
  employeeName: string;
  fee;
  invoiceCode: string;
  invoiceType: string;
  paid;
  paymentType: string;
  phone: string;
  receiptDate: string;
  receiptImage: string;
  referId: number;
  status: number;
  updatedTime: string;
  vatAmount: number;
}

export interface ICustomerExchangeResponseModel {
  medias: string;
  media: string;
  id: number;
  content: string;
  contentDelta: string;
  employeeId: number;
  employeeName: string;
  employeeAvatar: string;
  employeeUserId: number;
  type: number;
  customerId: number;
  createdTime: string;
}

export interface ICustomerFeedbackResponseModel {
  id: number;
  content: string;
  contentDelta: string;
  employeeId: number;
  employeeName: string;
  employeeAvatar: string;
  employeeUserId: number;
  type: number;
  customerId: number;
  createdTime: string;
  media?: string;
  medias?: string;
}
