// Dữ liệu mẫu cho Grid Hồ sơ mời thầu
export const headerHsmt = [
  {
    key: "TenHoSo",
    name: "Tên hồ sơ",
    type: "text",
    lookup: "",
    formula: '{"formula":""}',
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: '{"startDate":"","endDate":""}',
    listBindingField: [],
  },
  {
    key: "HoSoMoiThau",
    name: "Hồ sơ mời thầu",
    type: "checkbox",
    lookup: "",
    formula: '{"formula":""}',
    options: [
      {
        label: "",
        value: "",
      },
    ],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: '{"startDate":"","endDate":""}',
    listBindingField: [],
  },
  {
    key: "HoSoDuThau",
    name: "Hồ sơ dự thầu",
    type: "checkbox",
    lookup: "",
    formula: '{"formula":""}',
    options: [
      {
        label: "",
        value: "",
      },
    ],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: '{"startDate":"","endDate":""}',
    listBindingField: [],
  },
  {
    key: "documentType",
    name: "documentType",
    type: "text",
    lookup: "",
    formula: '{"formula":""}',
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: '{"startDate":"","endDate":""}',
    listBindingField: [],
  },
];

export const dataRowHsmt: any = [
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "",
      lookup: "",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      noteList: [],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      noteList: [],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "",
      lookup: "",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
    },
  ],
  {
    type: "title",
    style: "title-H3",
    rowKey: "07e2d505-7c9c-45c8-99f6-0a0b1e77dfb0",
    content: "Hồ sơ kỹ thuật",
    indexTitle: "",
    isShowEdit: false,
  },
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Phạm vi công việc",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "PVCV",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Danh mục vật tư",
      lookup: "",
      rowKey: "aaf3e4d5-2926-4d18-9c17-fc3c5d1f56f7",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "aaf3e4d5-2926-4d18-9c17-fc3c5d1f56f7",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "aaf3e4d5-2926-4d18-9c17-fc3c5d1f56f7",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "DMVT",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Yêu cầu kĩ thuật",
      lookup: "",
      rowKey: "3d406134-0b50-4d24-90d3-21ab9109175a",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "3d406134-0b50-4d24-90d3-21ab9109175a",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "3d406134-0b50-4d24-90d3-21ab9109175a",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "YCKT",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Tiêu chí thí nghiệm",
      lookup: "",
      rowKey: "20be66da-ae45-41ce-acc4-d35af765fbdf",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "20be66da-ae45-41ce-acc4-d35af765fbdf",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "20be66da-ae45-41ce-acc4-d35af765fbdf",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "TCTN",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Bản vẽ thiết kế",
      lookup: "",
      rowKey: "12b0a8b6-dd64-466e-bb7b-ed1f15fab127",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "12b0a8b6-dd64-466e-bb7b-ed1f15fab127",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "12b0a8b6-dd64-466e-bb7b-ed1f15fab127",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "BVTK",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Hợp đồng mẫu",
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "HDM",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "BoQ",
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "BoQ",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  {
    type: "title",
    style: "title-H3",
    rowKey: "122c4707-9590-4780-aed8-257418c508c6",
    content: "Hồ sơ tài chính",
    indexTitle: "",
    isShowEdit: false,
  },
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Hồ sơ tài chính",
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: true,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      rowSpecialKey: "hstc",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: true,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "hstc",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
];
export const dataRowHsmtTvtk: any = [
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "",
      lookup: "",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      noteList: [],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      noteList: [],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "",
      lookup: "",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
    },
  ],
  {
    type: "title",
    style: "title-H3",
    rowKey: "07e2d505-7c9c-45c8-99f6-0a0b1e77dfb0",
    content: "Hồ sơ kỹ thuật",
    indexTitle: "",
    isShowEdit: false,
  },
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Phạm vi công việc",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "PVCV",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Hợp đồng mẫu",
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "c6177968-60a1-4387-8ac5-c324f0715fff",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "HDM",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "BoQ",
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: false,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: false,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "BoQ",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
  {
    type: "title",
    style: "title-H3",
    rowKey: "122c4707-9590-4780-aed8-257418c508c6",
    content: "Hồ sơ tài chính",
    indexTitle: "",
    isShowEdit: false,
  },
  [
    {
      key: "TenHoSo",
      name: "Tên hồ sơ",
      type: "text",
      regex: "",
      value: "Hồ sơ tài chính",
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Tên hồ sơ",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
    {
      key: "HoSoMoiThau",
      name: "Hồ sơ mời thầu",
      type: "checkbox",
      regex: "",
      value: true,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      rowSpecialKey: "hstc",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ mời thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "HoSoDuThau",
      name: "Hồ sơ dự thầu",
      type: "checkbox",
      regex: "",
      value: true,
      lookup: "",
      rowKey: "a6ba21d2-214c-4215-a688-ba310fb01c43",
      formula: '{"formula":""}',
      options: [
        {
          label: "",
          value: "",
        },
      ],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "Hồ sơ dự thầu",
      bindingField: "",
      listBindingField: [],
    },
    {
      key: "documentType",
      name: "documentType",
      type: "text",
      regex: "",
      value: "hstc",
      lookup: "",
      rowKey: "41cba702-5d17-42c8-825b-e860c921bae8",
      formula: '{"formula":""}',
      options: [],
      readOnly: true,
      required: false,
      showNote: false,
      isBinding: false,
      timeRange: '{"startDate":"","endDate":""}',
      placeholder: "documentType",
      bindingField: "",
      isRegexFalse: false,
      listBindingField: [],
    },
  ],
];
