%%{init: {'theme':'base','themeVariables':{'fontFamily':'Calibri','fontSize':'18px'}}}%%
flowchart TB
    subgraph CLIENT["Client Tier"]
      direction LR
      POS[POS Terminal<br/>Chrome/Edge + máy in bill]
      BROWSER[Admin/Sales Browser]
      MOB[Mobile Web<br/>nhân viên kho]
    end

    subgraph EDGE["Edge / CDN Tier"]
      CF[Cloudflare / CDN<br/>static cache]
      WAF[WAF + DDoS]
    end

    subgraph LB["Load Balancer Tier"]
      ALB[Application Load Balancer<br/>TLS termination]
    end

    subgraph APP["Application Tier — Kubernetes"]
      direction TB
      SPA[Frontend SPA<br/>Nginx static]
      GW[API Gateway<br/>URL prefix routing]
      subgraph MS["Microservices (Pods)"]
        direction LR
        P_SALES[sales-svc]
        P_INV[inventory-svc]
        P_WH[warehouse-svc]
        P_PUR[purchase-svc]
        P_FIN[finance-svc]
        P_BILL[billing-svc]
        P_MKT[market-svc]
        P_NOTIF[notification-svc]
        P_AUTH[auth-svc]
      end
    end

    subgraph DATA["Data Tier"]
      direction LR
      PG[(PostgreSQL<br/>primary + replica)]
      REDIS[(Redis cluster<br/>cache + session)]
      S3[(S3 / MinIO<br/>file, image, bill PDF)]
      MQ[(RabbitMQ / Kafka)]
    end

    POS --> CF
    BROWSER --> CF
    MOB --> CF
    CF --> WAF
    WAF --> ALB
    ALB --> SPA
    ALB --> GW
    GW --> MS
    MS --> PG
    MS --> REDIS
    MS --> S3
    MS --> MQ

    classDef client fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef edge fill:#D97706,stroke:#7C2D12,color:#fff
    classDef app fill:#2C7A7B,stroke:#0F4C44,color:#fff
    classDef data fill:#FAEEDA,stroke:#D97706,color:#7C2D12

    class POS,BROWSER,MOB client
    class CF,WAF,ALB edge
    class SPA,GW,P_SALES,P_INV,P_WH,P_PUR,P_FIN,P_BILL,P_MKT,P_NOTIF,P_AUTH app
    class PG,REDIS,S3,MQ data
