%%{init: {'theme':'base','themeVariables':{'fontFamily':'Calibri','fontSize':'18px'}}}%%
flowchart TB
    INTERNET((Internet))
    subgraph CLOUD["Cloud Provider"]
      subgraph PUB["Public Subnet"]
        CDN[CDN — CloudFlare]
        WAF[WAF]
        LB[Load Balancer<br/>2× HA]
        NAT[NAT Gateway]
      end
      subgraph PRIV_APP["Private Subnet — App tier"]
        K8S["Kubernetes cluster"]
        BASTION[Bastion / SSH]
      end
      subgraph PRIV_DATA["Private Subnet — Data tier"]
        PG_M[(PostgreSQL<br/>Master)]
        PG_R1[(Replica 1)]
        PG_R2[(Replica 2)]
        PG_R3[(Replica 3 — reports)]
        REDIS_C[(Redis Cluster<br/>3 nodes)]
        S3_INT[(Object Storage)]
      end
    end

    subgraph EXT["External"]
      SSO[SSO Reborn]
      VAT[E-invoice]
      PAY[Payment Gateway]
      SMS[SMS / Email / Zalo]
    end

    INTERNET --> CDN
    CDN --> WAF
    WAF --> LB
    LB --> K8S
    K8S --> PG_M
    K8S --> PG_R1
    K8S --> PG_R2
    K8S --> PG_R3
    K8S --> REDIS_C
    K8S --> S3_INT
    K8S --> NAT
    NAT --> SSO
    NAT --> VAT
    NAT --> PAY
    NAT --> SMS
    BASTION -.SSH.-> K8S
    PG_M -.replication.-> PG_R1
    PG_M -.replication.-> PG_R2
    PG_M -.replication.-> PG_R3

    classDef ext fill:#FEF3C7,stroke:#F59E0B,color:#78350F
    classDef pub fill:#E1F5EE,stroke:#2C7A7B,color:#0F4C44
    classDef app fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef data fill:#FAEEDA,stroke:#D97706,color:#7C2D12

    class INTERNET,SSO,VAT,PAY,SMS ext
    class CDN,WAF,LB,NAT pub
    class K8S,BASTION app
    class PG_M,PG_R1,PG_R2,PG_R3,REDIS_C,S3_INT data
