%%{init: {'theme':'base','themeVariables':{'fontFamily':'Calibri','fontSize':'18px'}}}%%
flowchart LR
    USER((Receptionist))
    POS[POS Page]
    SS[Sales Service]
    INVS[Inventory Service]
    FS[Finance Service]
    CS[Care Service]
    NOTIF[Notification Service]

    DB1[(invoice<br/>invoice_item)]
    DB2[(warehouse_stock<br/>stock_issue)]
    DB3[(cashbook)]
    DB4[(loyalty_wallet)]
    DB5[(audit_log)]
    DB6[(shift)]

    USER -->|click thanh toán| POS
    POS -->|POST invoice/create| SS
    SS -->|INSERT| DB1
    SS -->|trừ tồn| INVS
    INVS -->|UPDATE| DB2
    SS -->|sinh phiếu thu| FS
    FS -->|INSERT| DB3
    SS -->|cộng điểm| CS
    CS -->|UPDATE| DB4
    SS -->|ghi audit| DB5
    SS -->|cập nhật ca| DB6
    SS -->|trigger event| NOTIF
    NOTIF -.->|push notification| USER

    classDef user fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef svc fill:#2C7A7B,stroke:#0F4C44,color:#fff
    classDef db fill:#FAEEDA,stroke:#D97706,color:#7C2D12

    class USER,POS user
    class SS,INVS,FS,CS,NOTIF svc
    class DB1,DB2,DB3,DB4,DB5,DB6 db
