%%{init: {'theme':'base','themeVariables':{'fontFamily':'Calibri','fontSize':'18px'}}}%%
flowchart TB
    subgraph INTERNET["Internet"]
      USERS[POS Terminals<br/>Browsers<br/>Mobile]
    end

    subgraph EDGE["Edge / Public"]
      CDN[CDN<br/>Cloudflare]
      WAF[WAF + DDoS Protection]
    end

    subgraph VPC["VPC — Production Region"]
      direction TB
      subgraph PUB["Public Subnet (multi-AZ)"]
        ALB[Application Load Balancer<br/>TLS 1.3]
        NAT[NAT Gateway]
      end

      subgraph PRV_APP["Private Subnet — App (multi-AZ)"]
        direction LR
        subgraph K8S["Kubernetes Cluster"]
          SPA_POD[Frontend SPA<br/>Nginx pods]
          GW_POD[API Gateway pods]
          MS_POD[Microservice pods<br/>sales/inventory/warehouse<br/>finance/billing/care<br/>market/notification/auth]
          WRK[Worker pods<br/>webhook, marketplace sync,<br/>batch jobs]
        end
      end

      subgraph PRV_DATA["Private Subnet — Data (multi-AZ)"]
        PG_P[(PostgreSQL Primary)]
        PG_R[(PostgreSQL Replica<br/>read-only)]
        REDIS[(Redis Cluster)]
        MQ[(RabbitMQ/Kafka cluster)]
      end

      subgraph STORAGE["Object Storage + Backup"]
        S3[(S3 bucket<br/>images, bill PDF,<br/>einvoice XML)]
        BK[(DB Backup<br/>daily snapshot<br/>+ PITR WAL)]
      end

      subgraph OBS["Observability"]
        PROM[Prometheus]
        GRAF[Grafana]
        ELK[ELK Stack<br/>log aggregation]
        SENTRY[Sentry<br/>error tracking]
      end
    end

    USERS --> CDN
    CDN --> WAF
    WAF --> ALB
    ALB --> SPA_POD
    ALB --> GW_POD
    GW_POD --> MS_POD
    MS_POD --> WRK
    MS_POD --> PG_P
    MS_POD --> PG_R
    MS_POD --> REDIS
    MS_POD --> MQ
    WRK --> MQ
    WRK --> PG_P
    MS_POD --> S3
    PG_P --> BK
    MS_POD -.metrics.-> PROM
    PROM --> GRAF
    MS_POD -.logs.-> ELK
    MS_POD -.errors.-> SENTRY
    WRK --> NAT
    NAT --> INTERNET

    classDef net fill:#1F3A68,stroke:#1F3A68,color:#fff
    classDef edge fill:#D97706,stroke:#7C2D12,color:#fff
    classDef app fill:#2C7A7B,stroke:#0F4C44,color:#fff
    classDef data fill:#FAEEDA,stroke:#D97706,color:#7C2D12
    classDef obs fill:#7C3AED,stroke:#5B21B6,color:#fff

    class USERS,ALB,NAT net
    class CDN,WAF edge
    class SPA_POD,GW_POD,MS_POD,WRK app
    class PG_P,PG_R,REDIS,MQ,S3,BK data
    class PROM,GRAF,ELK,SENTRY obs
