export interface IProductResponse {
  id: number;
  name: string;
  avatar?: string;
  code?: string;
  productLine?: string;
  position?: number;
  status: number;
  unitId?: number;
  unitName?: string;
  price?: number;
  priceWholesale?: number;
  pricePromo?: number;
  costPrice?: number;
  type?: number;
  otherUnits: string;
  exchange?: number;
  description?: string;
  supplierId?: number | null;
  categoryId?: number | null;
  categoryName?: string;
  trackStock?: boolean;
  stock?: number;
  stockWarning?: number;
  minStock?: number;
  maxStock?: number;
  showOnWeb?: boolean;
  showOnWebsite?: boolean | number;
  showImage?: boolean;
  showUnit?: boolean;
  showDesc?: boolean;
  showPromoPrice?: boolean;
  showWholesalePrice?: boolean;
  showStock?: boolean;
  showBarcode?: boolean;
  showCategory?: boolean;
  hideWhenOutOfStock?: boolean;
  defaultVariantId?: number;
  variantCount?: number;
  variantGroupCount?: number;
  variantGroups?: any[];
  variants?: any[];
  bsnId?: number;
  hashedLink?: string;
  pageTitle?: string;
  pageDescription?: string;
  pageKeyword?: string;
  expiredPeriod?: number;
  minQuantity?: number;
  documents?: any;
}
